# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Publish package on new release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with: 
        java-version: '8'
        distribution: 'zulu'
        cache: 'maven'

    - name: Publish package
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: target/*.jar
        overwrite: true
        file_glob: true
